# Generated by Django 4.1 on 2022-08-09 15:30

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=7)),
                ('sub_catg', models.CharField(max_length=7)),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=7)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('price', models.CharField(max_length=50, verbose_name='price($)')),
                ('sold', models.IntegerField(blank=True, null=True)),
                ('mugshot', models.ImageField(blank=True, null=True, upload_to=store.models.path)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=50)),
                ('sub_catg', models.CharField(max_length=7)),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=5)),
                ('sold', models.IntegerField()),
                ('price', models.CharField(max_length=50, verbose_name='price($)')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
