# Generated by Django 4.1 on 2022-10-10 17:48

from django.db import migrations, models
import django.db.models.deletion
import store.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=20, unique=True, verbose_name='barcode')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('sub_catg', models.CharField(blank=True, max_length=20, null=True, verbose_name='sub-category')),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('cost_price', models.CharField(max_length=20, validators=[store.models.castValidator], verbose_name='cost price($)')),
                ('selling_price', models.CharField(max_length=20, validators=[store.models.castValidator], verbose_name='selling price($)')),
                ('sold', models.IntegerField(blank=True, null=True)),
                ('returned', models.IntegerField(blank=True, null=True)),
                ('mugshot', models.ImageField(blank=True, null=True, upload_to=store.models.path)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('serial_no', models.UUIDField(default=uuid.uuid4, help_text='an auto generated uuid4 string for transaction ID', primary_key=True, serialize=False)),
                ('buyer', models.CharField(max_length=20)),
                ('attendant', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=20, verbose_name='barcode')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('sub_catg', models.CharField(blank=True, max_length=20, null=True)),
                ('sold', models.IntegerField()),
                ('cost_price', models.CharField(max_length=20)),
                ('selling_price', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='store.transaction')),
            ],
        ),
    ]
