# Generated by Django 4.1.7 on 2023-09-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('manager', 'manager'), ('supervisor', 'supervisor'), ('attendant', 'attendant')], max_length=12),
        ),
    ]
