# Generated by Django 4.1.7 on 2023-09-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('manager', 'manager'), ('supervisor', 'supervisor'), ('attendant', 'attendant')], help_text='This field define the user access level to the store panel.', max_length=12),
        ),
    ]
