# Generated by Django 4.1.7 on 2023-12-16 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date_test',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 13, 49, 16, 128118, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
