# Generated by Django 4.1 on 2022-08-17 06:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_sale_sub_catg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='id',
        ),
        migrations.AlterField(
            model_name='sale',
            name='serial_no',
            field=models.UUIDField(default=uuid.uuid4, help_text='an auto generated uuid4 string for sales ID', primary_key=True, serialize=False),
        ),
    ]
