# Generated by Django 4.1.7 on 2023-12-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sale_date_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Return',
            new_name='Returns',
        ),
    ]
