# Generated by Django 4.1 on 2022-09-06 07:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_sale_id_alter_sale_serial_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('serial_no', models.UUIDField(default=uuid.uuid4, help_text='an auto generated uuid4 string for transaction ID', primary_key=True, serialize=False)),
                ('buyer', models.CharField(max_length=30)),
                ('attendant', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='store.transaction'),
        ),
    ]
