# Generated by Django 4.1.7 on 2023-12-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_return_returns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='date',
        ),
    ]
