# Generated by Django 4.1.7 on 2023-12-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_test',
            field=models.DateField(auto_now_add=True),
        ),
    ]
