# Generated by Django 4.1.7 on 2023-12-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_sale_date_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sub_catg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='sub-category'),
        ),
    ]
